sudo: required

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=unstable
  - TRAVIS_DEBIAN_DISTRIBUTION=testing
  - TRAVIS_DEBIAN_DISTRIBUTION=stable

matrix:
  allow_failures:
    - env: TRAVIS_DEBIAN_DISTRIBUTION=unstable

services:
  - docker

script:
  # build the debian package
  - wget -O- http://travis.debian.net/script.sh | sh -

#notifications:
#  email: false

branches:
  except:
    - /^debian\/\d/
